<?php
class Contact{
    private $id;
    private $contact_Name;
    private $phone;
    private $email;
    private $category;
    private $contact_Image;

    public function __construct($contact_Name, $phone, $email, $category, $contact_Image, $id = null) {
        $this->contact_Name = $contact_Name;
        $this->phone = $phone;
        $this->email = $email;
        $this->category = $category;   
        $this->contact_Image = $contact_Image;
        $this->id = $id;
    }
    //id will be autogenerated by the database.

    // Getters
    public function getId() {
        return $this->id;
    }

    public function getcontact_Name() {
        return $this->contact_Name;
    }

    public function getPhone() {
        return $this->phone;
    }

    public function getEmail() {
        return $this->email;
    }

    public function getCategory() {
        return $this->category;
    }

    public function getcontact_Image() {
        return $this->contact_Image;
    }

    // Setters
    public function setcontact_Name($contact_Name) {
        $this->contact_Name = $contact_Name;
    }

    public function setPhone($phone) {
        $this->phone = $phone;
    }
    
    public function setEmail($email) {
        $this->email = $email;
    }

    public function setCategory($category) {
        $this->category = $category;
    }

    public function setcontact_Image($contact_Image) {
        $this->contact_Image = $contact_Image;
    }   

    public function setId($id) {
        $this->id = $id;
    }
}
?>