name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from GitHub
      uses: actions/checkout@v4

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.TEST_SECRET }}" > ~/.ssh/key_pair
        chmod 600 ~/.ssh/key_pair

    - name: SSH into EC2 and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.16.171.230.114 }} << 'EOF'
          # Commands to update the app on the EC2 instance
          cd /path/to/your/application
          git pull origin main
          
          # If you're using Node.js, for example
          npm install
          php install
          
          # If it's a PHP or static app, just restart the web server
          sudo systemctl restart httpd

        EOF
